### ISSUE TITLE
성호준씨 보시오

### ISSUE THREAD

**Issue by ylb7274** [shj0303/litekkutu#1]
게임 중 붙여넣기 방지 해제가 가능합니다.
그리고 게임 GM이 20명이라는데 대체 뭔가요?

**Comment by shj0303** [comment]
GM 20명인건 원래 이섭이 친목섭이었기도 하고 지금 접은사람도 많고 저, 부계 등등이 많이 있기 때문에 실질적으로는 10명쯤이라고 볼 수 있어요 복붙방지 해제는 모르겠네요
